### ISSUE TITLE
Problem compiler and run

### ISSUE THREAD

**Issue by kapsule** [KeenMate/svelte-adminlte#4]
Hi. thank you very much for this repository. i was looking for a svelte environment with admin-lte. after downloading the project i tried to compile it with the following commands but it didn't work. is there anything i should take into account?

git clone https://github.com/KeenMate/svelte-adminlte.git
cd svelte-adminlte
npm install
npm run dev

many thanks!!!

**Comment by OndrejValenta** [comment]
:-) we have not really expected someone else using this repo but it's nice. :-)

Anyway, is there some kind of error you get? Could you post a screenshot here? 

Btw. This repository just contains the components and so on, to use it you need to use it in another project, our example project is here: https://github.com/KeenMate/phoenix-svelte-adminlte

**Comment by hectordufau** [comment]
Hi guys!

I did the same as @kapsule and I got the same result: "npm run dev" runs, but it opens just a white page.

I'm looking for a Svelte Admin LTE template too (without Elixir, only node + svelte).

Would you like help us @OndrejValenta ?

**Comment by kapsule** [comment]
Hi @OndrejValenta. Thank you very much for your reply :)

I found it very interesting to find an admin panel in svelte on admin lte. For that reason, I wanted to test it to see if I could use it as a base for a client portal I want to make (an open source project).

The problem I have encountered is that when compiling the project with (npm run dev) the system reports several warnings. However, it finally starts the service to be able to access it from the browser. The problem is that when accessing from the browser the system does not show anything (blank page).

**Comment by OndrejValenta** [comment]
Guys, don't forget it's Christmas and New year, and we were focusing more on that. 

That being said, we have decided to create a new repository that would serve as a template for new admin console, we do quite a lot of PoCs and it's tireing to do the same steps over and over again. 

The new repo is here and it's work in progress: https://github.com/KeenMate/rollup-svelte-adminlte-template

This repo is a base for all cut out components that will be packed into an npm package.

We discussed on Friday how to do it properly and we'll follow how Vuetify does it so there is going to be a dev folder with simple test page that does not end up in the npm package.

**Comment by kapsule** [comment]
Hi @OndrejValenta and happy New Year.

Thank you very much for your comment. I will follow the new repository to be able to test.

**Comment by OndrejValenta** [comment]
@TheMaikXX commited the first version of the template, as we would use it, with some comments on how to use it. 

Check it out here https://github.com/KeenMate/rollup-svelte-adminlte-template

Btw. @TheMaikXX and I agreed on friday it would be best approach to keep this package "independent" on npm package of AdminLTE, meaning this once-to-be package does not contain all compiled css and javascript of AdminLTE, so when you want to use svelte-adminlte components in a project that project has to also use AdminLTE npm package and import their scss and so on. You can see it in the template.

**Comment by OndrejValenta** [comment]
Just an update from yesterday's session.. this library has been even more cleaned of any admin-lte and all references were moved to https://github.com/KeenMate/rollup-svelte-adminlte-template 

There is a readme that describes where is what there I just have to fix it a little bit but now even scss and admin-lte variables work
