### ISSUE TITLE
Version demo is not iqual github

### ISSUE THREAD

**Issue by megavision** [KeenMate/svelte-adminlte#6]
hi!
Your version is diferent. Not contains all components in the git 

thank you if update the github.

**Comment by FilipJakab** [comment]
Hello,
I'm sorry if I misunderstood your issue (a clarification would be helpful perhaps) but this project does not contain all components the original AdminLTE provides (at least not at the moment). As of now, we already use this library from within our [Svelte project template](https://github.com/KeenMate/rollup-svelte-adminlte-template) And the library provides decent amount of components to get you started with AdminLTE.

PS: We also advise to use our project template as it already has setup for AdminLTE with our components. For existing projects, the template can serve as a guidance on how to set it up.

**Comment by megavision** [comment]
Hi
is that the github page does not contain the same components as the project documentation page itself.
Some components are missing.
https://phoenix-svelte-adminlte.demo.keenmate.com/#/components

**Comment by ZelvaMan** [comment]
Hello, 
that's because that page uses dev branch. It will be merged with main after we check that everything is working properly.

**Comment by megavision** [comment]
thank you so much! I managed to understand how the project is structured.
*José Rubenildo da Silva*
*Analista de Sistemas*
*Celular 65 9 92392791 Whatsapp*



Em qui., 13 de jan. de 2022 às 17:01, Jan Rada ***@***.***>
escreveu:
