### ISSUE TITLE
full example

### ISSUE THREAD

**Issue by megavision** [KeenMate/svelte-adminlte#7]
Hi
full example
As a suggestion you could put the complete example with the import in the documentation.

Grateful

**Comment by megavision** [comment]
![image](https://user-images.githubusercontent.com/4016127/149522102-7f8347dc-a36f-4c98-aebb-bdf93367ca37.png)

**Comment by ZelvaMan** [comment]
Hello, 
thanks for the suggestion,I will look into it.
