### ISSUE TITLE
documents

### ISSUE THREAD

**Issue by megavision** [KeenMate/svelte-adminlte#8]
Hi
How do I use this template in a Svelte project.
The documentation has me download it as an example.
the one on this link https://phoenix-svelte-adminlte.demo.keenmate.com/#/components

**Comment by ZelvaMan** [comment]
Hello,
I am not sure if I understand your question correctly. You can find the source code to that website at [KeenMate/phoenix-svelte-adminlte](https://github.com/KeenMate/phoenix-svelte-adminlte). We have also created a template for creating new SPA svelte administration. You can find it [here](https://github.com/KeenMate/rollup-svelte-adminlte-template). Just follow instructions in the readme. I hope this answers your question.
